In [ ]:
import numpy as np
a = np.array([[1,2],[4,6]])
b = np.array([[7,8],[10,11]])
print("printing the elements of the first matrix")
print(a)
print("printing the elements of the second matrix")
print(b)
print("printing the sum of the two matrices")   
c = a + b
print(c)

In [3]:
import numpy as np
 
 
# creating first matrix
A = np.array([[1, 2], [3, 4]])
 
# creating second matrix
B = np.array([[4, 5], [6, 7]])
 
print("Printing elements of first matrix")
print(A)
print("Printing elements of second matrix")
print(B)
 
# adding two matrix
print("Addition of two matrix")
print(np.add(A, B))

Printing elements of first matrix
[[1 2]
 [3 4]]
Printing elements of second matrix
[[4 5]
 [6 7]]
Addition of two matrix
[[ 5  7]
 [ 9 11]]
